### ISSUE TITLE
install issue on Mac

### ISSUE THREAD

**Issue by decalage2** [decalage2/oletools#141]
Issue reported by @evild3ad after installing oletools on a new Mac:

I tried to install 0.50 via pip and the dev...and tested it with olevba, oleid, mraptor and rtfobj.

mraptor and rtfobj are giving me following errors:

```
MacBookPro:oletools $ rtfobj
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/rtfobj",
line 9, in <module>
    load_entry_point('oletools==0.51a1', 'console_scripts', 'rtfobj')()
  File
"/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line
549, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File
"/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line
2709, in load_entry_point
    return ep.load()
  File
"/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line
2369, in load
    return self.resolve()
  File
"/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line
2379, in resolve
    raise ImportError(str(exc))
ImportError: 'module' object has no attribute 'main'
MacBookPro:oletools $ mraptor
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/mraptor",
line 9, in <module>
    load_entry_point('oletools==0.51a1', 'console_scripts', 'mraptor')()
  File
"/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line
549, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File
"/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line
2709, in load_entry_point
    return ep.load()
  File
"/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line
2369, in load
    return self.resolve()
  File
"/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line
2375, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named mraptor
```
Same errors when installing 0.50 via pip:

```
MacBookPro:oletools $ rtfobj  
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/rtfobj",
line 9, in <module>
    load_entry_point('oletools==0.50', 'console_scripts', 'rtfobj')()
  File
"/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line
549, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File
"/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line
2709, in load_entry_point
    return ep.load()
  File
"/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line
2369, in load
    return self.resolve()
  File
"/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line
2379, in resolve
    raise ImportError(str(exc))
ImportError: 'module' object has no attribute 'main'

MacBookPro:oletools $ mraptor
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/mraptor",
line 9, in <module>
    load_entry_point('oletools==0.50', 'console_scripts', 'mraptor')()
  File
"/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line
549, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File
"/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line
2709, in load_entry_point
    return ep.load()
  File
"/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line
2369, in load
    return self.resolve()
  File
"/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line
2375, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named mraptor
```

This is strange because rtfobj does have a main() function. 
Need to test if the same issue occurs on other Macs:
- On OSX 10.11.6 with Python 2.7.10: no issue.

**Comment by decalage2** [comment]
More tests from @evild3ad:

MacBook 1: OSX 10.11.6 with Python 2.7.13 and pip 9.0.1 (native OS X Python + sudo easy_install pip)

oleid         OK
olemeta     OK
oletimes    OK

oledir        ERROR
```
oledir 0.50 - http://decalage.info/python/oletools
Traceback (most recent call last):
  File "/usr/local/bin/oledir", line 9, in <module>
    load_entry_point('oletools==0.50', 'console_scripts', 'oledir')()
  File "/Library/Python/2.7/site-packages/oletools/oledir.py", line 124,
in main
    fname = sys.argv[1]
IndexError: list index out of range
```
olemap     ERROR
```
olemap 0.50 - http://decalage.info/python/oletools
Traceback (most recent call last):
  File "/usr/local/bin/olemap", line 9, in <module>
    load_entry_point('oletools==0.50', 'console_scripts', 'olemap')()
  File "/Library/Python/2.7/site-packages/oletools/olemap.py", line 97,
in main
    fname = sys.argv[1]
IndexError: list index out of range
```
olevba     OK
mraptor     OK
oleobj     -bash: oleobj: command not found --> TODO, right?
rtfobj     OK

###############################################

MacBook 2: macOS 10.12.3 with Python 2.7.13 and pip 9.0.1
(native OS X Python + sudo easy_install pip)

oleid         OK
olemeta     OK
oletimes    OK
oledir         ERROR
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/oledir",
line 7, in <module>
    from oletools.oledir import main
ImportError: No module named oledir
```
olemap     ERROR
```
MacBookPro:~ $ olemap
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/olemap",
line 7, in <module>
    from oletools.olemap import main
ImportError: No module named olemap
```
olevba     OK
mraptor     ERROR
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/mraptor",
line 7, in <module>
    from oletools.mraptor import main
ImportError: No module named mraptor
```
oleobj     -bash: oleobj: command not found --> TODO, right?
rtfobj     ERROR
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/rtfobj",
line 7, in <module>
    from oletools.rtfobj import main
ImportError: cannot import name main
```
 
I also tested installing Python with homebrew...same results.

**Comment by decalage2** [comment]
I think all the tools should now work fine when installed with pip or just unzipped into a folder, using python 2 or 3, and display help when no filename is given.
