### ISSUE TITLE
Error Parsing RTF with rtfobj

### ISSUE THREAD

**Issue by securitykitten** [decalage2/oletools#164]
Hello, When using rtfobj to parse the file (sha256: 87311feacc477e9aff1331292fbb7cfcf010754137d948a0551193cb1c9e7932) it'll crash.

Output:
~~~~
rtfobj 87311feacc477e9aff1331292fbb7cfcf010754137d948a0551193cb1c9e7932.rtf 

rtfobj 0.51dev5 - http://decalage.info/python/oletools
THIS IS WORK IN PROGRESS - Check updates regularly!
Please report any issue at https://github.com/decalage2/oletools/issues

===============================================================================
File: '87311feacc477e9aff1331292fbb7cfcf010754137d948a0551193cb1c9e7932.rtf' - size: 620899 bytes
---+----------+-------------------------------+-------------------------------
id |index     |OLE Object                     |OLE Package                    
---+----------+-------------------------------+-------------------------------
Traceback (most recent call last):
  File "/usr/bin/rtfobj", line 9, in <module>
    load_entry_point('oletools==0.51.dev4', 'console_scripts', 'rtfobj')()
  File "/usr/lib/python2.7/site-packages/oletools-0.51.dev4-py2.7.egg/oletools/rtfobj.py", line 850, in main
    save_object=options.save_object)
  File "/usr/lib/python2.7/site-packages/oletools-0.51.dev4-py2.7.egg/oletools/rtfobj.py", line 701, in process_file
    ole_column += 'data size: %d' % rtfobj.oledata_size
TypeError: %d format: a number is required, not NoneType
~~~~

I've posted a copy of the RTF for analysis here (CAUTION LIVE SAMPLE)  -> https://drive.google.com/open?id=0B6sLf2D8GZIQTldjbk5WYlhPN1U with a password of "infected123"

**Comment by decalage2** [comment]
Thanks a lot for reporting this bug. Indeed, rtfobj was not taking into account OLE objects of type "linked" rather than "embedded". It is now fixed, and the object type is displayed next to the format id:
```
rtfobj 0.51dev7 - http://decalage.info/python/oletools
THIS IS WORK IN PROGRESS - Check updates regularly!
Please report any issue at https://github.com/decalage2/oletools/issues

===============================================================================
File: '87311feacc477e9aff1331292fbb7cfcf010754137d948a0551193cb1c9e7932.rtf' - size: 620899 bytes
---+----------+-------------------------------+-------------------------------
id |index     |OLE Object                     |OLE Package
---+----------+-------------------------------+-------------------------------
0  |0003D472h |format_id: 1 (Linked)          |Not an OLE Package
   |          |class name: ''                 |
   |          |data size: N/A                 |
---+----------+-------------------------------+-------------------------------
1  |0003D54Ch |format_id: 2 (Embedded)        |Not an OLE Package
   |          |class name: 'Word.Document.12' |
   |          |data size: 14336               |
---+----------+-------------------------------+-------------------------------
Saving raw data in object #0:
  saving object to file 87311feacc477e9aff1331292fbb7cfcf010754137d948a0551193cb1c9e7932.rtf_object_0003D472.raw
Saving file embedded in OLE object #1:
  format_id  = 2
  class name = 'Word.Document.12'
  data size  = 14336
  saving to file 87311feacc477e9aff1331292fbb7cfcf010754137d948a0551193cb1c9e7932.rtf_object_0003D54C.doc
```
