### ISSUE TITLE
pyxswf as does mraptor crashes on Microsoft Word 2007+

### ISSUE THREAD

**Issue by tshaw** [decalage2/oletools#172]
$ file /opt/mail_attachments/benign/94363cd0aa2c98c72c4a500bc324b15bcbb3c8cbac8f8d943313308ee24644b6.docx
/opt/mail_attachments/benign/94363cd0aa2c98c72c4a500bc324b15bcbb3c8cbac8f8d943313308ee24644b6.docx: Microsoft Word 2007+

/usr/local/bin/pyxswf
[sample.zip](https://github.com/decalage2/oletools/files/1066742/sample.zip)
 -o /opt/mail_attachments/benign/94363cd0aa2c98c72c4a500bc324b15bcbb3c8cbac8f8d943313308ee24644b6.docx

pyxswf 0.50 - http://decalage.info/python/oletools
Please report any issue at https://github.com/decalage2/oletools/issues

Traceback (most recent call last):
  File "/usr/local/bin/pyxswf", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/oletools/pyxswf.py", line 122, in main
    ole = olefile.OleFileIO(filename)
  File "/usr/local/lib/python2.7/dist-packages/oletools/thirdparty/olefile/olefile.py", line 1199, in __init__
    self.open(filename, write_mode=write_mode)
  File "/usr/local/lib/python2.7/dist-packages/oletools/thirdparty/olefile/olefile.py", line 1308, in open
    self._raise_defect(DEFECT_FATAL, "not an OLE2 structured storage file")
  File "/usr/local/lib/python2.7/dist-packages/oletools/thirdparty/olefile/olefile.py", line 1221, in _raise_defect
    raise exception_type(message)

IOError: not an OLE2 structured storage file

/usr/local/bin/mraptor /opt/mail_attachments/benign/94363cd0aa2c98c72c4a500bc324b15bcbb3c8cbac8f8d943313308ee24644b6.docx
MacroRaptor 0.50 - http://decalage.info/python/oletools
This is work in progress, please report issues at https://github.com/decalage2/oletools/issues
----------+-----+----+--------------------------------------------------------
Result    |Flags|Type|File                                                    
----------+-----+----+--------------------------------------------------------
ERROR     |     |??? |/opt/mail_attachments/benign/94363cd0aa2c98c72c4a500bc32
          |     |    |4b15bcbb3c8cbac8f8d943313308ee24644b6.docx              
          |     |    |Failed to open file /opt/mail_attachments/benign/94363cd
          |     |    |0aa2c98c72c4a500bc324b15bcbb3c8cbac8f8d943313308ee24644b
          |     |    |6.docx is not a supported file type, cannot extract VBA 
          |     |    |Macros.                                                 

Flags: A=AutoExec, W=Write, X=Execute
Traceback (most recent call last):
  File "/usr/local/bin/mraptor", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/oletools/mraptor.py", line 331, in main
    print('Exit code: %d - %s' % (exitcode, global_result.name))
AttributeError: 'NoneType' object has no attribute 'name'

**Comment by decalage2** [comment]
Hi @tshaw, the file seems to be truncated and/or corrupt, hence the errors. Several tools such as Windows Explorer and Total Commander refuse to open the docx as a zip. 7-zip manages to extract files, but reports the following errors:
```
7za t 94363cd0aa2c98c72c4a500bc324b15bcbb3c8cbac8f8d943313308ee24644b6.docx.zip

7-Zip (a) 17.00 beta (x86) : Copyright (c) 1999-2017 Igor Pavlov : 2017-04-29
Scanning the drive for archives:
1 file, 131100 bytes (129 KiB)
Testing archive: 94363cd0aa2c98c72c4a500bc324b15bcbb3c8cbac8f8d943313308ee24644b6.docx.zip
ERRORS:
Unexpected end of archive
--
Path = 94363cd0aa2c98c72c4a500bc324b15bcbb3c8cbac8f8d943313308ee24644b6.docx.zip
Type = zip
ERRORS:
Unexpected end of archive
Physical Size = 193854
Characteristics = Local

ERROR: CRC Failed : word\media\image1.jpeg
``` 

So I'll check if the integrity errors can be ignored with Python zipfile, or at least if I can improve the error displayed by the tools.

**Comment by tshaw** [comment]
Yes just don't want the software to crash. Rather have it return known error code(s) on corrupted files so scripts can keep running.

File came in in active mail stream
