### ISSUE TITLE
olevba if installed with the python3 is not working

### ISSUE THREAD

**Issue by xambroz** [decalage2/oletools#176]
Hello,
if oletools are installed with "python3 setup.py install" the olevba is failing . This is related to #173:

```
$ olevba
Traceback (most recent call last):
  File "/usr/bin/olevba", line 9, in <module>
    load_entry_point('oletools==0.51.dev11', 'console_scripts', 'olevba')()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2575, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2235, in load
    return self.resolve()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2241, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.5/site-packages/oletools/olevba.py", line 238, in <module>
    import cStringIO
ImportError: No module named 'cStringIO'
```

I have noticed there is olevba3.py, which seems to be working with python3, but is outdated (comparing to current olevba.py) and not installed with the "python3 setup.py install". 

I would beg to merge the olevba3.py and olevba.py back together and have just one functioning for both python2 and python3 if possible.

The main syntax issue seems to be cStringIO.StringIO being called BytesIO in the python3.
It could be probably solved by having:

```
try:
    # Python 3
    from _io import BytesIO
except:
    # Python 2.7
    import cStringIO.StringIO as BytesIO
```

and then replacing all "cStringIO.StringIO" with BytesIO

I know there are some other syntax changes, but hopefuly some of them might be solved by "from _future_ import xxxx".

Thank you
Michal Ambroz

**Comment by Th4nat0s** [comment]
Not all... Things like are in the code

```
if isinstance(vba_code, bytes):
      vba_code = vba_code.decode('utf-8', 'backslashrep
          if isinstance(code,bytes):
             code=code.decode('utf-8','backslashreplace')
```

Already tried only the bytesIO :)

**Comment by decalage2** [comment]
Hi @xambroz, indeed I plan to merge olevba and olevba3: see issue #106.
I tried already a long time ago, there are several issues not easy to fix due to small differences between python 2 and 3, e.g. the behaviour of bytes is different even if it looks the same.
Right now I am lacking time, so the Py3 version is lagging behind.
