### ISSUE TITLE
msodde -  issue with Unicode

### ISSUE THREAD

**Issue by decalage2** [decalage2/oletools#258]
when running msodde 0.52dev11 on Windows 10 with python 2.7.14 to scan one of the test files (dde-in-word2007.xml), the following exception is raised:
```text
msodde 0.52dev11 - http://decalage.info/python/oletools
THIS IS WORK IN PROGRESS - Check updates regularly!
Please report any issue at https://github.com/decalage2/oletools/issues

Opening file: dde-in-word2007.xml
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python36-32\Scripts\msodde-script.py", line 11, in <module>
    load_entry_point('oletools==0.52.dev12', 'console_scripts', 'msodde')()
  File "c:\program files (x86)\python36-32\lib\site-packages\oletools\msodde.py", line 1018, in main
    text = process_file(args.filepath, args.field_filter_mode)
  File "c:\program files (x86)\python36-32\lib\site-packages\oletools\msodde.py", line 973, in process_file
    return process_csv(filepath)
  File "c:\program files (x86)\python36-32\lib\site-packages\oletools\msodde.py", line 856, in process_csv
    results, dialect = process_csv_dialect(file_handle, CSV_DELIMITERS)
  File "c:\program files (x86)\python36-32\lib\site-packages\oletools\msodde.py", line 887, in process_csv_dialect
    dialect = csv.Sniffer().sniff(file_handle.read(CSV_SMALL_THRESH),
  File "c:\program files (x86)\python36-32\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 5527: character maps to <undefined>
```

The issue seems to come from the new code to parse CSV files.

**Comment by christian-intra2net** [comment]
On linux with python 3.3.2 I get no error.

CSV-Parsing should not be attempted at all on this file, msodde should detect that this is a word xml file
