### ISSUE TITLE
ModuleNotFoundError: No module named 'cStringIO'

### ISSUE THREAD

**Issue by sasha2002** [decalage2/oletools#261]
C:\Users\sasha2002>olevba
Traceback (most recent call last):
  File "C:\Users\sasha2002\AppData\Local\Programs\Python\Python36\Scripts\olevba-script.py", line 11, in <module>
    load_entry_point('oletools==0.52.1', 'console_scripts', 'olevba')()
  File "c:\users\sasha2002\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\users\sasha2002\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "c:\users\sasha2002\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 2291, in load
    return self.resolve()
  File "c:\users\sasha2002\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\sasha2002\appdata\local\programs\python\python36\lib\site-packages\oletools\olevba.py", line 244, in <module>
    import cStringIO
ModuleNotFoundError: No module named 'cStringIO'

**Comment by decalage2** [comment]
Sorry @sasha2002, olevba only works on Python 2. On Python 3 you need to run **olevba3** instead.
