### ISSUE TITLE
olevba LookupError: unknown encoding

### ISSUE THREAD

**Issue by securitykitten** [decalage2/oletools#268]
When running olevba against a document the following error is displayed

```
$ olevba fdce84323cc9aaae25aa72f1c6a97f8b7f6b9ec0b5281a499e11918dfa3674ae
olevba 0.52 - http://decalage.info/python/oletools
Flags        Filename                                                         
-----------  -----------------------------------------------------------------
ERROR    Error in _extract_vba
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/oletools/olevba.py", line 2801, in extract_macros
    dir_path, self.relaxed):
  File "/usr/local/lib/python2.7/dist-packages/oletools/olevba.py", line 1712, in _extract_vba
    streamname_unicode = modulestreamname_streamname.decode(vba_codec)
LookupError: unknown encoding: cp0
OLE:MAS--B-- fdce84323cc9aaae25aa72f1c6a97f8b7f6b9ec0b5281a499e11918dfa3674ae
...snip...
```
A copy of the document can be downloaded here -> https://drive.google.com/open?id=1B21IvFWZPB3CTV7gzFTadwWITh7vhXPU

password: oletools

**Comment by securitykitten** [comment]
I changed my local instance to remove the bug by changing the line 
```
streamname_unicode = modulestreamname_streamname.decode(vba_codec)
```
to 
```
streamname_unicode = modulestreamname_streamname.decode(str(vba_codec))
```

I didn't commit the PR as I'm not sure if there is some larger effort around supporting different encodings.

**Comment by christian-intra2net** [comment]
A "more proper" fix would be to slightly extend the code in olevba.py line 1707 (vba_codec = 'cp%d' % projectcodepage_codepage) to (1) replace "0" with some default and (2) always check if the codepage created in that line exists and if not fall back to ascii.

Wikipedia mentions codepage 0 as reserved and "for internal OS use" (https://en.wikipedia.org/wiki/Code_page#List_of_code_page_assignments)
