### ISSUE TITLE
Test suite of oletools 0.52 fails with Python 2.7 on Fedora

### ISSUE THREAD

**Issue by robert-scheck** [decalage2/oletools#279]
Package maintainer of python-oletools from Fedora and EPEL (for RHEL/CentOS) here. The test suite of oletools 0.52 fails with Python 2.7 on Fedora as follows (while 0.51 worked charmingly) – any pointers?

```
Executing(%check): /bin/sh -e /var/tmp/rpm-tmp.kOJW5D
+ umask 022
+ cd /builddir/build/BUILD
+ cd oletools-0.52
+ /usr/bin/python2 setup.py test
running test
running egg_info
writing oletools.egg-info/PKG-INFO
writing top-level names to oletools.egg-info/top_level.txt
writing dependency_links to oletools.egg-info/dependency_links.txt
writing entry points to oletools.egg-info/entry_points.txt
reading manifest file 'oletools.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'oletools/README.txt'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
writing manifest file 'oletools.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 304, in <module>
    main()
  File "setup.py", line 298, in main
    test_suite="tests",
  File "/usr/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/test.py", line 226, in run
    self.run_tests()
  File "/usr/lib/python2.7/site-packages/setuptools/command/test.py", line 248, in run_tests
    exit=False,
  File "/usr/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
ImportError: No module named tests
error: Bad exit status from /var/tmp/rpm-tmp.kOJW5D (%check)
    Bad exit status from /var/tmp/rpm-tmp.kOJW5D (%check)
RPM build errors:
Child return code was: 1
```

**Comment by robert-scheck** [comment]
Unfortunately this issue still exists as per 0.53.1

**Comment by decalage2** [comment]
In Dec 2018, we modified MANIFEST.in to include the tests directory. @robert-scheck, could you please check if this issue is still open?

**Comment by robert-scheck** [comment]
Closing because issue #482 occurs with newer oletools instead.
