### ISSUE TITLE
Tools not working

### ISSUE THREAD

**Issue by keydet89** [decalage2/oletools#287]
Running Python 2.7.13 on Windows 10, successfully installed oletools 0.5.2 via pip.

Ran mraptor-script.py against a known malicious file:
C:\Python27\Scripts>python mraptor-script.py d:\cases\ir\doc\document.doc.malware
Traceback (most recent call last):
  File "mraptor-script.py", line 11, in <module>
    load_entry_point('oletools==0.52', 'console_scripts', 'mraptor')()
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2291, in load
    return self.resolve()
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named mraptor

Running olemeta-script.py against the same document:
C:\Python27\Scripts>olemeta-script.py d:\cases\ir\doc\document.doc.malware
Properties from SummaryInformation stream:
- codepage: 1251
- title: None
- subject: None
...snip...
- doc_version: None
Traceback (most recent call last):
  File "C:\Python27\Scripts\olemeta-script.py", line 11, in <module>
    load_entry_point('oletools==0.52', 'console_scripts', 'olemeta')()
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2291, in load
    return self.resolve()
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2301, in resolve
    raise ImportError(str(exc))
ImportError: 'module' object has no attribute 'main'

**Comment by decalage2** [comment]
Normally I do not run scripts directly from C:\Python27\Scripts\, instead I just run "olevba", "vmonkey", etc (without the .py extension). If you installed oletools with pip, there should be olevba.exe, vmonkey.exe, etc available from any directory. Could you please try these and tell me if it works? 
```
mraptor d:\cases\ir\doc\document.doc.malware
olemeta d:\cases\ir\doc\document.doc.malware
```

**Comment by decalage2** [comment]
I tested similar commands with Windows 10 and Python 2.7.14 and pip 9.0.3, from the python scripts directory, and for me it works. Maybe you could upgrade pip to the latest version (just in case), and then reinstall oletools? For that you need to run the following as administrator:
```
pip install -U pip
```
And then as a normal user:
```
pip install -I oletools
```

**Comment by keydet89** [comment]
C:\Python27>mraptor d:\cases\ir\doc\document.doc.malware
Traceback (most recent call last):
  File "C:\Python27\Scripts\mraptor-script.py", line 11, in <module>
    load_entry_point('oletools==0.52', 'console_scripts', 'mraptor')()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2291, in load
    return self.resolve()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named mraptor

C:\Python27>olemeta d:\cases\ir\doc\document.doc.malware
Properties from SummaryInformation stream:
- codepage: 1251
- title: None
- subject: None
- author: '\xcf\xee\xeb\xfc\xe7\xee\xe2\xe0\xf2\xe5\xeb\xfc Windows'
- keywords: None
- comments: None
- template: 'Normal.dotm'
- last_saved_by: '\xcf\xee\xeb\xfc\xe7\xee\xe2\xe0\xf2\xe5\xeb\xfc Windows'
- revision_number: '5'
- total_edit_time: 1320L
- last_printed: None
- create_time: datetime.datetime(2017, 9, 26, 12, 48)
- last_saved_time: datetime.datetime(2017, 9, 26, 13, 10)
- num_pages: 1
- num_words: 0
- num_chars: 1
- thumbnail: None
- creating_application: 'Microsoft Office Word'
- security: 0
Properties from DocumentSummaryInformation stream:
- codepage_doc: 1251
- category: None
- presentation_target: None
- bytes: None
- lines: 1
- paragraphs: 1
- slides: None
- notes: None
- hidden_slides: None
- mm_clips: None
- scale_crop: False
- heading_pairs: None
- titles_of_parts: None
- manager: None
- company: 'Microsoft'
- links_dirty: False
- chars_with_spaces: 1
- unused: None
- shared_doc: False
- link_base: None
- hlinks: None
- hlinks_changed: False
- version: 917504
- dig_sig: None
- content_type: None
- content_status: None
- language: None
- doc_version: None
Traceback (most recent call last):
  File "C:\Python27\Scripts\olemeta-script.py", line 11, in <module>
    load_entry_point('oletools==0.52', 'console_scripts', 'olemeta')()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2291, in load
    return self.resolve()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2301, in resolve
    raise ImportError(str(exc))
ImportError: 'module' object has no attribute 'main'
