### ISSUE TITLE
olevba3: unicode error

### ISSUE THREAD

**Issue by decalage2** [decalage2/oletools#323]
From @balin77 in #267: 

Hi, thank you very much for your code. Its very useful and saved my but. But now I am encountering similar troubles. Im using olevba3 --code. This works fine up to some point. then I get this:

```
ERROR    Unhandled exception in main: Error processing file 
C:\Users\...Filename.xlsm ('charmap' codec can't encode 
character '\u03f0' in position 582: character maps to <undefined>)
Traceback (most recent call last):
File "c:\users\.....\programs\python\python36-32\lib\site- 
packages\oletools\olevba3.py", line 3221, in process_file
print(vba_code_filtered)
File "c:\users\.....\appdata\local\programs\python\python36-32\lib\encodings\cp1252.py", line 19, in encode
 return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u03f0' in position 582: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\.....appdata\local\programs\python\python36-32\lib\site-packages\oletools\olevba3.py", line 3607, in main
    deobfuscate=options.deobfuscate)
  File "c:\users\......\appdata\local\programs\python\python36-32\lib\site-packages\oletools\olevba3.py", line 3241, in process_file
    raise ProcessingError(self.filename, exc)
oletools.olevba3.ProcessingError: Error processing file 
C:\Users\...Filename.xlsm ('charmap' codec can't encode character '\u03f0' in position 582: character maps to <undefined>)
```

**Comment by decalage2** [comment]
Similar error reported by Malwrologist @DissectMalware with sample https://www.hybrid-analysis.com/sample/d3978014176291973f9f2031f57f4dcee736d206a1c48b1e64f347b72005ce78?environmentId=100

The error is triggered even when redirecting the output to a file or to the clipboard.

potential solutions: https://stackoverflow.com/questions/4374455/how-to-set-sys-stdout-encoding-in-python-3

**Comment by decalage2** [comment]
Or maybe try unidecode? https://github.com/iki/unidecode

**Comment by balin77** [comment]
hey. thank you for responding. I checked the code of my VBA code and I actually had some strange symbols included. When I deleted them, it worked. As soon as I find some time, I will try some of the other solutions, you provided. 

The program stumbled a few modules later again, but instead of posting the new problem here I will check first the other open issues. Maybe there is a solution for it. Otherwise I will open a new Issue. Thanks very much

**Comment by decalage2** [comment]
Possibly another sample with same error: https://twitter.com/DissectMalware/status/1017271657550041088 reported by @DissectMalware
