### ISSUE TITLE
Oleid PrettyTable thirdparty import not working

### ISSUE THREAD

**Issue by obilodeau** [decalage2/oletools#391]
**Affected tool:**

oleid

**Describe the bug**

Tool crashes because it cannot use `PrettyTable`.

**File/Malware sample to reproduce the bug**

Any document would work

**How To Reproduce the bug**

From git repo:

```
virtualenv .
source bin/activate
python setup.py install
./bin/oleid sample.doc
```

Output:
```
oleid 0.54dev4 - http://decalage.info/oletools
THIS IS WORK IN PROGRESS - Check updates regularly!
Please report any issue at https://github.com/decalage2/oletools/issues

Filename: [snip]
Traceback (most recent call last):
  File "./bin/oleid", line 11, in <module>
    load_entry_point('oletools==0.54.dev8', 'console_scripts', 'oleid')()
  File "/home/olivier/src/oletools/lib/python3.7/site-packages/oletools-0.54.dev8-py3.7.egg/oletools/oleid.py", line 487, in main
    table = prettytable.PrettyTable(['Indicator', 'Value'])
AttributeError: module 'oletools.thirdparty.prettytable' has no attribute 'PrettyTable'
```

**Expected behavior**

The tool should work with the appropriate output.

**Console output / Screenshots**

See above.

**Version information:**
 - OS: Linux
 - OS version: Arch Linux 64 bits
 - Python version: 3.7 and 2.7
 - oletools version: git master (setuptool said 0.54.dev8 but `oleid` prints 0.54.dev4)

**Additional context**

Problem is reproducible in both Python 2 and 3 environments. See python2 stack trace:

```
oleid sample.doc 
oleid 0.54dev4 - http://decalage.info/oletools
THIS IS WORK IN PROGRESS - Check updates regularly!
Please report any issue at https://github.com/decalage2/oletools/issues

Filename: [snip]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/oletools/oleid.py", line 500, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/oletools/oleid.py", line 487, in main
    table = prettytable.PrettyTable(['Indicator', 'Value'])
AttributeError: 'module' object has no attribute 'PrettyTable'
```

Note that this time it is not through a `virtualenv` of the git repo but a blackarch install of 0.54dev4.

Also, I'm going to submit a PR to fix this.

**Comment by obilodeau** [comment]
PR is here: #392
