### ISSUE TITLE
olemap - bytes/str error on Python 3

### ISSUE THREAD

**Issue by decalage2** [decalage2/oletools#394]
triggered with this sample: https://www.hybrid-analysis.com/sample/09e890f9aaedd64021274a6729272a95f358d1a1771ca43758b778303cd35281?environmentId=100

```
olemap 0.54dev1 - http://decalage.info/python/oletools
-------------------------------------------------------------------------------
FILE: 09e890f9aaedd64021274a6729272a95f358d1a1771ca43758b778303cd35281.bin

OLE HEADER:
+------------------------+----------------+-----------------------------------+
|Attribute               |Value           |Description                        |
+------------------------+----------------+-----------------------------------+
|OLE Signature (hex)     |D0CF11E0A1B11AE1|Should be D0CF11E0A1B11AE1         |
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\Scripts\olemap-script.py", line 11, in <module>
    load_entry_point('oletools==0.54.dev8', 'console_scripts', 'olemap')()
  File "c:\program files (x86)\python37-32\lib\site-packages\oletools\olemap.py", line 281, in main
    show_header(ole, extra_data=options.extra_data)
  File "c:\program files (x86)\python37-32\lib\site-packages\oletools\olemap.py", line 124, in show_header
    t.write_row(['Header CLSID (hex)', binascii.b2a_hex(ole.header_clsid).upper(), 'Should be 0'])
TypeError: a bytes-like object is required, not 'str'
```

**Comment by Maijin** [comment]
This is fixed:

```
olemap ~/Downloads/09e890f9aaedd64021274a6729272a95f358d1a1771ca43758b778303cd35281
olemap 0.54 - http://decalage.info/python/oletools
-------------------------------------------------------------------------------
FILE: /Users/maijin/Downloads/09e890f9aaedd64021274a6729272a95f358d1a1771ca43758b778303cd35281

OLE HEADER:
+------------------------+----------------+-----------------------------------+
|Attribute               |Value           |Description                        |
+------------------------+----------------+-----------------------------------+
|OLE Signature (hex)     |D0CF11E0A1B11AE1|Should be D0CF11E0A1B11AE1         |
|Header CLSID (hex)      |                |Should be 0                        |
|Minor Version           |003E            |Should be 003E                     |
|Major Version           |0003            |Should be 3 or 4                   |
|Byte Order              |FFFE            |Should be FFFE (little endian)     |
|Sector Shift            |0009            |Should be 0009 or 000C             |
|# of Dir Sectors        |0               |Should be 0 if major version is 3  |
|# of FAT Sectors        |2               |                                   |
|First Dir Sector        |00000001        |(hex)                              |
|Transaction Sig Number  |0               |Should be 0                        |
|MiniStream cutoff       |4096            |Should be 4096 bytes               |
|First MiniFAT Sector    |00000077        |(hex)                              |
|# of MiniFAT Sectors    |2               |                                   |
|First DIFAT Sector      |FFFFFFFE        |(hex)                              |
|# of DIFAT Sectors      |0               |                                   |
+------------------------+----------------+-----------------------------------+

CALCULATED ATTRIBUTES:
+------------------------+----------------+-----------------------------------+
|Attribute               |Value           |Description                        |
+------------------------+----------------+-----------------------------------+
|Sector Size (bytes)     |512             |Should be 512 or 4096 bytes        |
|Actual File Size (bytes)|87559           |Real file size on disk             |
|Max File Size in FAT    |131584          |Max file size covered by FAT       |
|Extra data beyond FAT   |0               |Only if file is larger than FAT    |
|                        |                |coverage                           |
|Extra data offset in FAT|00015600        |Offset of the 1st free sector at   |
|                        |                |end of FAT                         |
|Extra data size         |7               |Size of data starting at the 1st   |
|                        |                |free sector at end of FAT          |
+------------------------+----------------+-----------------------------------+

To display the FAT or MiniFAT structures, use options --fat or --minifat, and -h for help.
```

**Comment by decalage2** [comment]
For me it works on Windows with Python 2.7, but not with Python 3.7. I'll investigate further.

**Comment by Maijin** [comment]
@decalage2 Actually, that's because my TableStream branch is fixing this issue - https://github.com/decalage2/oletools/pull/466

<img width="927" alt="image" src="https://user-images.githubusercontent.com/1408600/60986569-10680e00-a340-11e9-8961-a2dd53445cda.png">

**Comment by decalage2** [comment]
Mmh... on your screenshot it looks like you ran the 2nd test with python2.7 instead of 3.7.
Anyway it's a simple bug, I'll fix it right away.

**Comment by Maijin** [comment]
oh right whoops 😸 !
