### ISSUE TITLE
olevba/crypto: FileNotFoundError when source file is in a zip

### ISSUE THREAD

**Issue by decalage2** [decalage2/oletools#420]
Example:
```
c:>olevba DIAN_caso-5415.doc.zip -z infected
olevba 0.54 on Python 3.7.2 - http://decalage.info/python/oletools
===============================================================================
FILE: DIAN_caso-5415.doc.malware in DIAN_caso-5415.doc.zip
Type: OLE
-------------------------------------------------------------------------------
[...]
Sub Workbook_Open()
    Auto_Open
End Sub

+----------+--------------------+---------------------------------------------+
|Type      |Keyword             |Description                                  |
+----------+--------------------+---------------------------------------------+
|AutoExec  |AutoOpen            |Runs when the Word document is opened        |
|AutoExec  |Auto_Open           |Runs when the Excel Workbook is opened       |
|AutoExec  |Workbook_Open       |Runs when the Excel Workbook is opened       |
|Suspicious|Environ             |May read system environment variables        |
|Suspicious|Shell               |May run an executable file or a system       |
|          |                    |command                                      |
|Suspicious|Lib                 |May run code from a DLL                      |
|Suspicious|URLDownloadToFileA  |May download files from the Internet         |
|IOC       |http://germanya.com.|URL                                          |
|          |ec/logs/test.exe    |                                             |
|IOC       |http://germanya.com.|URL                                          |
|          |ec/logs/counter.php |                                             |
|IOC       |test.exe            |Executable file name                         |
|IOC       |sfjozjero.exe       |Executable file name                         |
+----------+--------------------+---------------------------------------------+

ERROR    Unhandled exception in main: [Errno 2] No such file or directory: 'DIAN_caso-5415.doc.malware'
Traceback (most recent call last):
  File "c:\program files (x86)\python37-32\lib\site-packages\oletools\olevba.py", line 3839, in process_file
    if not crypto.is_encrypted(filename):
  File "c:\program files (x86)\python37-32\lib\site-packages\oletools\crypto.py", line 205, in is_encrypted
    return is_encrypted_ole(OleFileIO(some_file))
  File "c:\program files (x86)\python37-32\lib\site-packages\olefile\olefile.py", line 1075, in __init__
    self.open(filename, write_mode=write_mode)
  File "c:\program files (x86)\python37-32\lib\site-packages\olefile\olefile.py", line 1169, in open
    self.fp = open(filename, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'DIAN_caso-5415.doc.malware'
```

**Comment by christian-intra2net** [comment]
Could you send me the sample? Could try to bugfix

**Comment by Maijin** [comment]
@decalage2 @christian-intra2net I tried reproducing using https://www.virustotal.com/gui/file/5762576fc6a09b4ddd95908c6c34ab9b38e06a6b2878099433347cabfbeccc18/detection in a zip encrypted archive with infected password and filename  DIAN_caso-5415.doc.malware but I can't reproduce.

**Comment by christian-intra2net** [comment]
I have never encountered this, either. But I am hardly ever working on zipped input

**Comment by christian-intra2net** [comment]
Sorry if this is a stupid question: everybody posts links about samples on virustotal but with my free account there I seem to be unable to download them and a premium key is quite costly. Do you guys all have premium access or am I missing something?

**Comment by decalage2** [comment]
Same here. Usually I get the hash and then look for it on other sites that provide samples without paid subscription (hybrid-analysis, app.any.run, etc). I made a custom google search engine to do this: http://www.decalage.info/en/mwsearch

**Comment by Maijin** [comment]
If you need a specific sample from VT let me know

**Comment by christian-intra2net** [comment]
I see, thanks a lot for the link!
