### ISSUE TITLE
Error while decrypting a password protected sample

### ISSUE THREAD

**Issue by Heat-Miser** [decalage2/oletools#453]
**Affected tool:**
olevba

**Describe the bug**
Olevba raises an error while decrypting the provided sample.

```
$>olevba -p 12345678 candidature_1288.doc 
olevba 0.55.dev2 on Python 2.7.16 - http://decalage.info/python/oletools
===============================================================================
FILE: candidature_1288.doc
Type: OLE
No VBA macros found.

WARNING  msoffcrypto failed to interpret file candidature_1288.doc or determine whether it is encrypted: 'OOXMLFile' object has no attribute 'is_encrypted'
ERROR    Unhandled exception in main: 'OOXMLFile' object has no attribute 'is_encrypted'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/oletools/olevba.py", line 4160, in main
    curr_return_code = process_file(filename, data, container, options)
  File "/usr/local/lib/python2.7/site-packages/oletools/olevba.py", line 4055, in process_file
    decrypted_file = crypto.decrypt(filename, passwords)
  File "/usr/local/lib/python2.7/site-packages/oletools/crypto.py", line 379, in decrypt
    if not crypto_file.is_encrypted():
AttributeError: 'OOXMLFile' object has no attribute 'is_encrypted'

```
**File/Malware sample to reproduce the bug**
Here is the sample, the file is in a zip password protected with infected as password, and the doc is protected with 12345678.

[sample_pwd_infected.zip](https://github.com/decalage2/oletools/files/3261461/sample_pwd_infected.zip)

**How To Reproduce the bug**
```
$>olevba -p 12345678 candidature_1288.doc 
```

**Expected behavior**
I understand the the file should be decrypted and then olevba should be able to extract the macros.

**Console output / Screenshots**

```
$>olevba -l debug -p 12345678 candidature_1288.doc 
olevba 0.55.dev2 on Python 2.7.16 - http://decalage.info/python/oletools
INFO     Opening OLE file candidature_1288.doc
INFO     Check whether OLE file is PPT
DEBUG    using open OleFileIO
DEBUG    File appears not to be a ppt file (In stream "root" for field "listdir" found value "[u'encryptedpackage', u'encryptioninfo']" but expected Current User!)
===============================================================================
FILE: candidature_1288.doc
Type: OLE
DEBUG    VBA_Parser.find_vba_projects
DEBUG    Checking DirEntry #0
DEBUG    Checking DirEntry #1
DEBUG    Reading data from stream u'EncryptionInfo' - size: 248 bytes
DEBUG    Read 248 bytes
DEBUG    '\x03\x00\x02\x00$\x00\x00\x00\xa4\x00\x00\x00$\x00\x00\x00\x00\x00\x00\x00\x0ef\x00\x00\x04\x80\x00\x00\x80\x00\x00\x00\x18\x00\x00\x00\xa0\xc7\xdc\x02\x00\x00\x00\x00M\x00i\x00c\x00r\x00o\x00s\x00o\x00f\x00t\x00 \x00E\x00n\x00h\x00a\x00n\x00c\x00e\x00d\x00 \x00R\x00S\x00A\x00 \x00a\x00n\x00d\x00 \x00A\x00'...[much more data]...'H~\xd6\x8e\x14\xdc)$\x81\xe0\x92\xc49\xcf\x14\x00\x00\x00q\x87\xc415\xa2D\x96\xdf\x8d3\xd8\\\x893H\xc1h\xd5\xae\x1c\xf8n9\xb8\x8c\xd8\x0e\x84$BC'
DEBUG    Checking DirEntry #2
DEBUG    Reading data from stream u'EncryptedPackage' - size: 241512 bytes
DEBUG    Read 241512 bytes
DEBUG    "Q\xaf\x03\x00\x00\x00\x00\x00s!OKC\xc4\xd0\x99k\x04F\xae\xc6)\xc3\x10\xb5\xb7\xb7\xfd\x88\xa1\xfc\x95=\xae\x92'/\x04|A\xe2\xf8b\x18#\xb99\xb6\xbe@]|\xdd>x\xa2\xfeD\xa2\xe9\xaa*\xe7\x81\xd0V>\xd2\xc2\x92{[\xdb}\xcf\xba\x89M\xdb?\xc6n_\xed\x91\xa6\xde\x9d\xcb\x8b\xdc\xad\xda\x13K\x95]\xd9\xdfL"...[much more data]..."\xcbd\x8d\x05\xa7\xb7\xa7\x16\x1d8''k\xe5\\X9\xca\x1fr#.\xf62\x14\\k\x80=\x1dTCT\xff\xbe\xdc2{u\x88.\xaaI\xc5\xf9\\\xf3\x7f7\x03"
DEBUG    Checking DirEntry #3
DEBUG    This DirEntry is an orphan or unused
No VBA macros found.

DEBUG    Checking for encryption (normal)
DEBUG    is_encrypted
DEBUG    Checking for encryption using msoffcrypto
WARNING  msoffcrypto failed to interpret file candidature_1288.doc or determine whether it is encrypted: 'OOXMLFile' object has no attribute 'is_encrypted'
DEBUG    Checking for encryption in OLE file
DEBUG    found stream EncryptionInfo
DEBUG    Checking encryption passwords ['12345678']
ERROR    Unhandled exception in main: 'OOXMLFile' object has no attribute 'is_encrypted'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/oletools/olevba.py", line 4160, in main
    curr_return_code = process_file(filename, data, container, options)
  File "/usr/local/lib/python2.7/site-packages/oletools/olevba.py", line 4055, in process_file
    decrypted_file = crypto.decrypt(filename, passwords)
  File "/usr/local/lib/python2.7/site-packages/oletools/crypto.py", line 379, in decrypt
    if not crypto_file.is_encrypted():
AttributeError: 'OOXMLFile' object has no attribute 'is_encrypted'
DEBUG    will exit now with code 8
```

**Version information:**
 - OS: Mac
 - OS version: Mojave 10.14.5 (18F132) 64 bits
 - Python version: Python 2.7.16 (default, Mar  4 2019, 09:01:38) 
 - oletools version: 0.55.dev2

**Comment by christian-intra2net** [comment]
That is what I call a proper issue report, well done!
@decalage2 You self-assigned this, so I stay out of it, ok?

**Comment by decalage2** [comment]
Well @christian-intra2net you may also have a look if you have time to check it. ;-)

**Comment by Heat-Miser** [comment]
> That is what I call a proper issue report, well done!
> @decalage2 You self-assigned this, so I stay out of it, ok?

Well you guys make an awesome work with Oletools, you deserve a correct issue :)

**Comment by christian-intra2net** [comment]
Must be a bug I fixed in one of my pull requests, I have no trouble scanning the file on my machine

**Comment by christian-intra2net** [comment]
And it really does look like malware:
```
+----------+--------------------+---------------------------------------------+
|Type      |Keyword             |Description                                  |
+----------+--------------------+---------------------------------------------+
|AutoExec  |Document_Open       |Runs when the Word or Publisher document is  |
|          |                    |opened                                       |
|Suspicious|Environ             |May read system environment variables        |
|Suspicious|Shell               |May run an executable file or a system       |
|          |                    |command                                      |
|Suspicious|Lib                 |May run code from a DLL                      |
|Suspicious|URLDownloadToFileA  |May download files from the Internet         |
|Suspicious|Base64 Strings      |Base64-encoded strings were detected, may be |
|          |                    |used to obfuscate strings (option --decode to|
|          |                    |see all)                                     |
|IOC       |https://asd.updateco|URL                                          |
|          |nfigvbsec.xyz/aaword|                                             |
|          |1.tmp               |                                             |
+----------+--------------------+---------------------------------------------+

```
