### ISSUE TITLE
Errors with square brackets in filenames

### ISSUE THREAD

**Issue by gnugnug** [decalage2/oletools#476]
I observe the following behaviour with different oletools programs, for example olevba: When trying to analyse a file that contains "[" "]" the file is silently ignored or an exception is raised. I placed the same document under 3 different filenames in a directory and tried to scan it, however olevba simply skips the one named "mymacros/macro[1].doc" and mraptor runs into an error:

```
$ shasum mymacros/*
f7bb6e0e7bd7444c128ab729c2eb959573ad104d  mymacros/macro[1].doc
f7bb6e0e7bd7444c128ab729c2eb959573ad104d  mymacros/macro2.doc
f7bb6e0e7bd7444c128ab729c2eb959573ad104d  mymacros/macro.doc

$ olevba "mymacros/macro.doc" "mymacros/macro[1].doc" "mymacros/macro2.doc"
olevba 0.54.2 on Python 3.6.8 - http://decalage.info/python/oletools
Flags        Filename
-----------  -----------------------------------
OLE:MA------ mymacros/macro.doc
OLE:MA------ mymacros/macro2.doc

(Flags: OpX=OpenXML, XML=Word2003XML, FlX=FlatOPC XML, MHT=MHTML, TXT=Text, M=Macros, A=Auto-executable, S=Suspicious keywords, I=IOCs, H=Hex strings, B=Base64 strings, D=Dridex strings, V=VBA strings, ?=Unknown)

$ mraptor "mymacros/macro[1].doc"
MacroRaptor 0.54 - http://decalage.info/python/oletools
This is work in progress, please report issues at https://github.com/decalage2/oletools/issues
----------+-----+----+--------------------------------------------------------
Result    |Flags|Type|File
----------+-----+----+--------------------------------------------------------

Flags: A=AutoExec, W=Write, X=Execute
Traceback (most recent call last):
  File "/usr/local/bin/mraptor", line 11, in <module>
    load_entry_point('oletools==0.54.2', 'console_scripts', 'mraptor')()
  File "/usr/local/lib/python3.6/site-packages/oletools/mraptor.py", line 349, in main
    print('Exit code: %d - %s' % (exitcode, global_result.name))
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by decalage2** [comment]
I guess this might be due to the fact that special chars like * and ? are use to select multiple files, and [] might also have a special behaviour.
Can you try escaping them with a backslash, e.g. `olevba "mymacros/macro\[1\].doc"` ?

**Comment by gnugnug** [comment]
Escaping does not help in my tests, neither does putting the filename in quotation marks or adding more backslashes:

```
$ olevba macro.doc macro\[1\].doc "macro[1].doc" "macro\[1\].doc" macro\\[1\\].doc "macro\\[1\\].doc" nonexistantfile
olevba 0.54.2 on Python 3.6.8 - http://decalage.info/python/oletools
Flags        Filename
-----------  -----------------------------------------------------------------
OLE:M------- macro.doc
?            nonexistantfile - File not found
```
macro[1].doc is recognized as an existing file, but is silently skipped while scanning.

**Comment by decalage2** [comment]
See also #588: similar issue, with potential solutions
