### ISSUE TITLE
Failing tests (even with up-to-date Python stack)

### ISSUE THREAD

**Issue by robert-scheck** [decalage2/oletools#482]
There are failing tests, even with up-to-date Python stack:
```
BUILDSTDERR: ERROR: test_rough_doctype (tests.ooxml.test_basic.TestOOXML)
BUILDSTDERR: Checks all samples, expect either ole files or good ooxml output
BUILDSTDERR: ----------------------------------------------------------------------
BUILDSTDERR: Traceback (most recent call last):
BUILDSTDERR:   File "/builddir/build/BUILD/oletools-0.54.2/tests/ooxml/test_basic.py", line 64, in test_rough_doctype
BUILDSTDERR:     acceptable = ext2doc[extn]
BUILDSTDERR: KeyError: 'txt'
BUILDSTDERR: ======================================================================
BUILDSTDERR: FAIL: test_crypt_return (tests.olevba.test_basic.TestOlevbaBasic)
BUILDSTDERR: ----------------------------------------------------------------------
BUILDSTDERR: Traceback (most recent call last):
BUILDSTDERR:   File "/builddir/build/BUILD/oletools-0.54.2/tests/olevba/test_basic.py", line 98, in test_crypt_return
BUILDSTDERR:     .format(ret_code, args + [filename, ]))
BUILDSTDERR: AssertionError: 0 != 9 : Wrong return code 0 for args ['test.txt']
BUILDSTDERR: ======================================================================
BUILDSTDERR: FAIL: test_encrypted (tests.msodde.test_basic.TestReturnCode)
BUILDSTDERR: ----------------------------------------------------------------------
BUILDSTDERR: Traceback (most recent call last):
BUILDSTDERR:   File "/builddir/build/BUILD/oletools-0.54.2/tests/msodde/test_basic.py", line 83, in test_encrypted
BUILDSTDERR:     WrongEncryptionPassword)
BUILDSTDERR:   File "/builddir/build/BUILD/oletools-0.54.2/tests/msodde/test_basic.py", line 101, in do_test_validity
BUILDSTDERR:     .format(expect_error, filename))
BUILDSTDERR: AssertionError: Expected <class 'oletools.common.errors.WrongEncryptionPassword'> but msodde finished without errors for /builddir/build/BUILD/oletools-0.54.2/tests/test-data/encrypted/test.txt
```

Used versions:

```
DEBUG util.py:587:   python3-colorclass          noarch      2.2.0-6.fc31           build      40 k
DEBUG util.py:587:   python3-devel               armv7hl     3.7.4-5.fc31           build     202 k
DEBUG util.py:587:   python3-easygui             noarch      0.96-25.fc31           build     478 k
DEBUG util.py:587:   python3-msoffcrypto         noarch      4.10.0-2.fc31          build      56 k
DEBUG util.py:587:   python3-olefile             noarch      0.46-4.fc31            build     4.7 M
DEBUG util.py:587:   python3-prettytable         noarch      0.7.2-18.fc31          build      41 k
DEBUG util.py:587:   python3-pymilter            armv7hl     1.0.4-2.fc31           build     115 k
DEBUG util.py:587:   python3-pyparsing           noarch      2.4.0-2.fc31           build     136 k
DEBUG util.py:587:   python-pip-wheel            noarch      19.1.1-4.fc31          build     1.1 M
DEBUG util.py:587:   python-pymilter-common      noarch      1.0.4-2.fc31           build     9.1 k
DEBUG util.py:587:   python-rpm-macros           noarch      3-47.fc31              build      13 k
DEBUG util.py:587:   python-setuptools-wheel     noarch      41.0.1-4.fc31          build     276 k
DEBUG util.py:587:   python3                     armv7hl     3.7.4-5.fc31           build      33 k
DEBUG util.py:587:   python3-asn1crypto          noarch      0.24.0-7.fc31          build     171 k
DEBUG util.py:587:   python3-cffi                armv7hl     1.12.3-1.fc31          build     231 k
DEBUG util.py:587:   python3-cryptography        armv7hl     2.6.1-2.fc31           build     505 k
DEBUG util.py:587:   python3-idna                noarch      2.8-2.fc31             build      96 k
DEBUG util.py:587:   python3-libs                armv7hl     3.7.4-5.fc31           build     6.6 M
DEBUG util.py:587:   python3-ply                 noarch      3.11-3.fc31            build     104 k
DEBUG util.py:587:   python3-py3dns              noarch      3.1.1-10.fc31          build      47 k
DEBUG util.py:587:   python3-pycparser           noarch      2.14-20.fc31           build     148 k
DEBUG util.py:587:   python3-rpm-generators      noarch      9-2.fc31               build      23 k
DEBUG util.py:587:   python3-rpm-macros          noarch      3-47.fc31              build      11 k
DEBUG util.py:587:   python3-setuptools          noarch      41.0.1-4.fc31          build     578 k
DEBUG util.py:587:   python3-six                 noarch      1.12.0-2.fc31          build      35 k
DEBUG util.py:587:   python3-tkinter             armv7hl     3.7.4-5.fc31           build     309 k
```

**Comment by decalage2** [comment]
@christian-intra2net, could you please have a look at those tests?

**Comment by christian-intra2net** [comment]
Ok. Hope to get to it tomorrow

**Comment by christian-intra2net** [comment]
There appears to be a file in oletools/tests/test-data/encrypted/test.txt that does not belong there.
One test (ooxml/test_zip_sub_file.py) creates a temporary zip file that includes a "test.txt" but that is created using mkstemp and should be removed by that test's fixture.
Any idea where that file comes from?
