### ISSUE TITLE
ValueError: bytes length not a multiple of item size

### ISSUE THREAD

**Issue by chchchchchchchch** [decalage2/oletools#491]
Traceback (most recent call last):
  File "E:/project/MaliciousMacroBot-master/obfuscatedbot/vbasamplemongo/vbatomongo.py", line 120, in <module>
    vbamongo.vba_to_mongo(["3206C441BC1F9403D751BAB812F29EF7"])
  File "E:/project/MaliciousMacroBot-master/obfuscatedbot/vbasamplemongo/vbatomongo.py", line 107, in vba_to_mongo
    extracted_vbalist = self.extracted_vba(sampledata)
  File "E:/project/MaliciousMacroBot-master/obfuscatedbot/vbasamplemongo/vbatomongo.py", line 70, in extracted_vba
    if vbaparser.detect_vba_macros():
  File "C:\Users\chenlu\AppData\Local\Programs\Python\Python37\lib\site-packages\oletools\olevba.py", line 3077, in detect_vba_macros
    data = ole._open(d.isectStart, d.size).read()
  File "C:\Users\chenlu\AppData\Local\Programs\Python\Python37\lib\site-packages\olefile\olefile.py", line 1793, in _open
    self.loadminifat()
  File "C:\Users\chenlu\AppData\Local\Programs\Python\Python37\lib\site-packages\olefile\olefile.py", line 1608, in loadminifat
    self.minifat = self.sect2array(s)
  File "C:\Users\chenlu\AppData\Local\Programs\Python\Python37\lib\site-packages\olefile\olefile.py", line 1455, in sect2array
    a = array.array(UINT32, sect)
ValueError: bytes length not a multiple of item size

**Comment by chchchchchchchch** [comment]
ValueError: bytes length not a multiple of item size
