### ISSUE TITLE
olemeta - IOError: not an OLE2 structured storage file

### ISSUE THREAD

**Issue by tr4px** [decalage2/oletools#496]
Olemeta fails to extract the meta information. However, on VT the information is available. Could this be a bug in parsing the storage files? I expect that the meta information should be displayed.

```
C:\Users\user\Desktop>olemeta file.doc
olemeta 0.54 - http://decalage.info/python/oletools
THIS IS WORK IN PROGRESS - Check updates regularly!
Please report any issue at https://github.com/decalage2/oletools/issues
===============================================================================
FILE: file.doc

Traceback (most recent call last):
  File "C:\Python27\Scripts\olemeta-script.py", line 11, in <module>
    load_entry_point('oletools==0.54.2', 'console_scripts', 'olemeta')()
  File "c:\python27\lib\site-packages\oletools\olemeta.py", line 173, in main
    ole = olefile.OleFileIO(filename)
  File "c:\python27\lib\site-packages\olefile\olefile.py", line 1075, in __init__
    self.open(filename, write_mode=write_mode)
  File "c:\python27\lib\site-packages\olefile\olefile.py", line 1192, in open
    self._raise_defect(DEFECT_FATAL, "not an OLE2 structured storage file")
  File "c:\python27\lib\site-packages\olefile\olefile.py", line 1105, in _raise_defect
    raise exception_type(message)
IOError: not an OLE2 structured storage file
```

Malware file to reproduce: https://ln2.sync.com/dl/faf39cf00#qr5s6qze-ccpmb97n-c2326wq2-7t4nyg72 (password: infected)

Python version: 2.7.14 - 32 bits

**Comment by decalage2** [comment]
Hi @tr4px, the file is actually an OpenXML file (Word 2007+), not an OLE/CFB file (Word 97-2003). For now, olemeta is only meant to support the latter. 
However, I agree that the error message could be improved. It should clearly state this, instead of a Python exception.

**Comment by tr4px** [comment]
- Are there any plans to support OpenXML files for olemeta?
- Do you know of other ways to retrieve the meta information of such formats?

**Comment by decalage2** [comment]
It would be a good idea, but for now there is no specific plan to implement it. 
There are other tools that can do it from the command line, such as exiftool: https://www.sno.phy.queensu.ca/~phil/exiftool/TagNames/OOXML.html
Or if you need a Python API:
- https://github.com/grierforensics/officedissector
- https://github.com/glenfant/openxmllib
- https://github.com/python-openxml/python-docx
