### ISSUE TITLE
Unable to find Macros in a "xlsm" file

### ISSUE THREAD

**Issue by vamrodia** [decalage2/oletools#583]
**Affected tool:**
olevba

**Describe the bug**
I am not able to check for Macros in a Malicious file using the OLEVBA tool. I am running the latest version.

**File/Malware sample to reproduce the bug**
f86c9c1f6bb45a9b4a208e7b45b77b1dec12f21f7ecc22c55894bea03fee1449

**Console output / Screenshots**

 olevba --loglevel=<filename>.xlsm
olevba 0.56dev6 on Python 2.7.17 - http://decalage.info/python/oletools
INFO     Opening ZIP/OpenXML file <filename>.xlsm
INFO     Failed Zip/OpenXML parsing for file '<filename>.xlsm' (Bad magic number for central directory)
DEBUG    Trace:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/oletools/olevba.py", line 2790, in open_openxml
    z = zipfile.ZipFile(_file)
  File "/usr/lib/python2.7/zipfile.py", line 793, in __init__
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 862, in _RealGetContents
    raise BadZipfile("Bad magic number for central directory")
BadZipfile: Bad magic number for central directory
INFO     <filename>.xlsm is not a supported file type, cannot extract VBA Macros.
DEBUG    Checking for encryption (after exception)
DEBUG    is_encrypted
DEBUG    Checking for encryption using msoffcrypto
ERROR    Failed to open <filename>.xlsm -- probably not supported!
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/oletools/olevba.py", line 4183, in process_file
    relaxed=options.relaxed)
  File "/usr/local/lib/python2.7/dist-packages/oletools/olevba.py", line 3771, in __init__
    super(VBA_Parser_CLI, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/oletools/olevba.py", line 2758, in __init__
    raise FileOpenError(msg)
FileOpenError: Failed to open file <filename>.xlsm is not a supported file type, cannot extract VBA Macros.
DEBUG    will exit now with code 5

**Version information:**
 - OS: Ubuntu 18.04
 - OS version: 64 bits
 - Python version: 2.7.17
 - oletools version:  0.56 dev6

**Additional context**

**Comment by decalage2** [comment]
Sample on any.run: https://app.any.run/tasks/17ddeecb-da40-405f-818a-34aca95bbe4f/
Looks like it's a malformed zip that python does not parse, but Excel opens it.

**Comment by vamrodia** [comment]
Hi Philippe,

It does look like it has Excel 4.0 Macro enabled in the file correct?

Thanks,
Vibhor
