### ISSUE TITLE
olevba can not 

### ISSUE THREAD

**Issue by shenhuanageshei** [decalage2/oletools#61]
Hello,when I use olevba.py -d to analyze a .xls sample,it return these:
**************************************************************************************************************
ERROR    Unhandled exception in main: 'ProcessingError' object has no attribute
'orig_exception'
Traceback (most recent call last):
  File "******\oletools\olevba.py", line 3292, in main
    print '%-12s %s - %s' % ('!ERROR', filename, exc.orig_exception)
AttributeError: 'ProcessingError' object has no attribute 'orig_exception'
**************************************************************************************************************
The sample's macro code can runing.. 
Sample's md5:c759babcfd296235e63f56ef8e3fd93d

**Comment by feiongithub** [comment]
yes , when I use 
vbaparser = VBA_Parser (this_file)
for v in vbaparser.extract_all_macros():
      pass
I got same exception :
File "C:\Python27\lib\site-packages\oletools\olevba.py", line 1350, in _extract_vba
    check_value('REFERENCE_Reserved', 0x003E, reference_reserved)
  File "C:\Python27\lib\site-packages\oletools\olevba.py", line 1206, in check_value
    raise UnexpectedDataError(dir_path, name, expected, value)
oletools.olevba.UnexpectedDataError: <exception str() failed>


I read the [MS-OVBA].pdf document , in 2.3.4.2.2.2 REFERENCENAME Record , It write : Reserved (2 bytes): MUST be 0x003E. MUST be ignored.  so the olevba.py handle it right .  hope someone give some advice.
