### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by ghanashyams** [decalage2/oletools#619]
**Affected tool:**
olevba latest 0.56dev

**Describe the bug**
Following stack is seen while scanning sample 0078fae36152dda270609a143aa492798288c232c43f9331dfea29251569cdfe.
Same error even if I try with --relaxed cmdline option.

python olevba.py 0078fae36152dda270609a143aa492798288c232c43f9331dfea29251569cdfe
Traceback (most recent call last):
File "olevba.py", line 3907, in process_file
self.run_analysis(show_decoded_strings=show_decoded_strings, deobfuscate=deobfuscate)
File "olevba.py", line 3803, in run_analysis
self.analyze_macros(show_decoded_strings, deobfuscate)
File "olevba.py", line 3427, in analyze_macros
for (_, _, _, vba_code) in self.extract_all_macros():
File "olevba.py", line 3406, in extract_all_macros
for (subfilename, stream_path, vba_filename, vba_code) in self.extract_macros():
File "olevba.py", line 3390, in extract_macros
if self.detect_vba_stomping():
File "olevba.py", line 3751, in detect_vba_stomping
vba_code_all_modules += vba_code + '\n'
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**File/Malware sample to reproduce the bug**
Sample file is attached, passcode- infected

**How To Reproduce the bug**
cmd line scan as mentined above

**Expected behavior**
Exception should not occur

**Console output / Screenshots**
python olevba.py 0078fae36152dda270609a143aa492798288c232c43f9331dfea29251569cdfe
Traceback (most recent call last):
File "olevba.py", line 3907, in process_file
self.run_analysis(show_decoded_strings=show_decoded_strings, deobfuscate=deobfuscate)
File "olevba.py", line 3803, in run_analysis
self.analyze_macros(show_decoded_strings, deobfuscate)
File "olevba.py", line 3427, in analyze_macros
for (_, _, _, vba_code) in self.extract_all_macros():
File "olevba.py", line 3406, in extract_all_macros
for (subfilename, stream_path, vba_filename, vba_code) in self.extract_macros():
File "olevba.py", line 3390, in extract_macros
if self.detect_vba_stomping():
File "olevba.py", line 3751, in detect_vba_stomping
vba_code_all_modules += vba_code + '\n'
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Version information:**
 - OS: Windows/Linux
 - OS version: x.xx - 64 bits
 - Python version: 3.7 - 64 bits
 - oletools version: 0.56dev latest

**Additional context**

**Comment by ghanashyams** [comment]
[Uploading 0078fae36152dda270609a143aa492798288c232c43f9331dfea29251569cdfe.zip…]()
passcode-  infected

**Comment by ghanashyams** [comment]
passcode- infected
[0078fae36152dda270609a143aa492798288c232c43f9331dfea29251569cdfe.zip](https://github.com/decalage2/oletools/files/5254813/0078fae36152dda270609a143aa492798288c232c43f9331dfea29251569cdfe.zip)

**Comment by decalage2** [comment]
I have not yet found a fix, but I see that the following exception is triggered when attempting to decompress the VBA source code: 
```
ValueError: Invalid CompressedChunkSignature in VBA compressed stream
```

**Comment by ninoseki** [comment]
Sorry I'm not confident it but how about check `vba_code` before yielding?

```python
# https://github.com/decalage2/oletools/blob/40faecbfc8b5de945929a42e36a88d6ae737bb85/oletools/olevba.py#L3333-L3344
            for vba_root, project_path, dir_path in self.vba_projects:
                # extract all VBA macros from that VBA root storage:
                # The function _extract_vba may fail on some files (issue #132)
                try:
                    for stream_path, vba_filename, vba_code in \
                            _extract_vba(self.ole_file, vba_root, project_path,
                                         dir_path, self.relaxed):
                        # store direntry ids in a set:
                        vba_stream_ids.add(self.ole_file._find(stream_path))

                        if vba_code is None:
                            raise ValueError

                        yield (self.filename, stream_path, vba_filename, vba_code)
                except Exception as e:
                    log.exception('Error in _extract_vba')
```
I will make a PR if this makes sense.

**Comment by decalage2** [comment]
I partially fixed the bug in olevba and mraptor, to avoid the error `TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'`.
The real root cause here is that the VBA compressed code is slightly malformed. This still needs to be handled properly in `decompress_stream`, so I'll keep the issue open until it is fully fixed.
This looks similar to issues #30 and #331.

**Comment by decalage2** [comment]
Yet another Emotet sample that triggers the same error: https://app.any.run/tasks/9665db2f-9ae5-4ffc-aaec-fb120dd41b9c/#

**Comment by Solumnant** [comment]
Other samples with the same error for files in https://github.com/fireeye/OfficePurge/tree/main/sample-data with _PURGE appened.

**Comment by decalage2** [comment]
This error is also triggered by the sample from issue #629
