### ISSUE TITLE
extract_macros (of VBA_PARSER) doesn't extract macrosheet code anymore

### ISSUE THREAD

**Issue by eyaltemps** [decalage2/oletools#728]
I'm not sure if this is a bug, or I'm missing a new feature or a specific action I should make, so i'll open it as a bug.

Affected tool: olevba

Bug description:
0.56.2 oletools version extracts macrosheets macro code by default when using "extract_macros()" but 0.60 oletools version doesn't.

File to reproduce the bug (password: Password1):
[food1.zip](https://github.com/decalage2/oletools/files/7784454/food1.zip)

How To Reproduce the bug:
**Python:**
```
vbaparser = VBA_Parser(file_path)
for (filename, stream_path, vba_filename, vba_code) in vbaparser.extract_macros():
      print(vba_code)
```
**CLI:**
Issue can be also seen with CLI command:
`olevba -jc {FILE_PATH}`

**Expected behavior**
Extracted macro code will contain macrosheet:
`"<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<xm:macrosheet.............."`
as happens in 0.56.2

Screenshots:
![0 56olevba](https://user-images.githubusercontent.com/69534979/147566618-47c224db-609f-46e1-b23f-bc6220c75174.PNG)
![0 60olevba](https://user-images.githubusercontent.com/69534979/147566621-10196503-6e88-4ed7-bc16-bbd4adec2a3a.PNG)

How can I make vbaparser.extract_macros() extract also the macrosheet code, as it worked in 0.56.2?

**Comment by eyaltemps** [comment]
Any advice to handle the issue with latest Olevba will be appreciated

**Comment by decalage2** [comment]
Hi @eyaltemps, indeed in 0.60 I made important changes on how XLM macros are extracted. I integrated XLMMacroDeobfuscator because it gives much better results than plugin_biff (thanks to emulation), and it supports more file formats. I removed the old code that was extracting XLM macros from xlsm because it was just giving raw XML. This is why you see no macro in your case.
If you install XLMMacroDeobfuscator it should fix your issue.

However, by default XLMMacroDeobfuscator is not installed by pip. You can either install it separately (see https://github.com/DissectMalware/XLMMacroDeobfuscator) or simply update oletools with this command:
```
pip install -U oletools[full]
```

**Comment by decalage2** [comment]
I need to check if olevba could fall back to the old code for XLSM if XLMMacroDeobfuscator is not available.

**Comment by decalage2** [comment]
The issue is actually due to a Unicode error when running XLMMacroDeobfuscator:
```
xlmdeobfuscator -c food1.xlsm
XLMMacroDeobfuscator: defusedxml is not installed (required to securely parse XLSM files)

XLMMacroDeobfuscator(v0.2.5) - https://github.com/DissectMalware/XLMMacroDeobfuscator

Traceback (most recent call last):
  File "c:\program files\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python39\Scripts\xlmdeobfuscator.exe\__main__.py", line 7, in <module>
  File "C:\Users\xxx\AppData\Roaming\Python\Python39\site-packages\XLMMacroDeobfuscator\deobfuscator.py", line 3125, in main
    defaults = json.load(config_file)
  File "c:\program files\python39\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "c:\program files\python39\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 14: invalid continuation byte
```
I will ask @DissectMalware to check this sample.

**Comment by eyaltemps** [comment]
@decalage2 Thank you,
Regardless the deobfuscation, is there any way to output the raw XML as it was in 0.56?
If not with Olevba, would you advice any other tool?

**Comment by decalage2** [comment]
I plan to reintegrate the old code that was extracting the raw xml as fallback, but I will need some time to do it. In the meantime, you can still use olevba 0.56 if it works better for you.

**Comment by DissectMalware** [comment]
The macrosheet seems to have only to formula

![image](https://user-images.githubusercontent.com/9646319/155471649-52fcbf00-e1b4-404b-a778-27637790b529.png)

![image](https://user-images.githubusercontent.com/9646319/155471719-5c98d8e4-11a0-48ea-acfa-f5d106bd5ba9.png)
