### ISSUE TITLE
olevba - errors "zero length field name in format" and "unexpected keyword argument 'exc_info'"

### ISSUE THREAD

**Issue by decalage2** [decalage2/oletools#75]
Issue submitted by SB AP-HP on Bitbucket in a comment: https://bitbucket.org/decalage/oletools/issues/43/oleid-macro-not-detected-in-docm-file

In my env, with Python 2.6.5, when i try olevba any doc: 2007 or 2010 i have some error: 

```text
./olevba.py -l debug ../COPY0000684.docm 

olevba 0.47 - http://decalage.info/python/oletools Flags Filename

INFO Opening ZIP/OpenXML file ../COPY0000684.docm 
DEBUG Opening OLE file word/vbaProject.bin within zip 
INFO Opening OLE file word/vbaProject.bin 
INFO Check whether OLE file is PPT 
DEBUG using open OleFileIO 
DEBUG File appears not to be a ppt file (zero length field name in format) 
DEBUG VBA_Parser.find_vba_projects 
DEBUG Checking storage [u'VBA'] 
DEBUG Found VBA storage: VBA 
DEBUG Checking vba_root="" 
DEBUG Found PROJECT stream: PROJECT 
DEBUG Found VBA/_VBA_PROJECT stream: VBA/_VBA_PROJECT 
DEBUG Found VBA/dir stream: VBA/dir 
DEBUG VBA root storage: "" 
DEBUG Checking DirEntry #0 
DEBUG Checking DirEntry #1 
DEBUG Checking DirEntry #2 
DEBUG Reading data from stream u'ThisDocument' - size: 1289 bytes 
DEBUG Read 1289 bytes 
DEBUG Error processing file ../COPY0000684.docm (zero length field name in format) 
Traceback (most recent call last): 
File "./olevba.py", line 3054, in process_file_triage if self.detect_vba_macros(): 
File "./olevba.py", line 2553, in detect_vba_macros if ole_subfile.detect_vba_macros(): 
File "./olevba.py", line 2584, in detect_vba_macros .format(repr(data[:100]), repr(data[-50:]))) ValueError: zero length field name in format 
Traceback (most recent call last): 
File "./olevba.py", line 3337, in <module> main() 
File "./olevba.py", line 3328, in main log.exception('Unhandled exception in main: %s' % exc, exc_info=True) 
TypeError: exception() got an unexpected keyword argument 'exc_info'
```

Thanks

**Comment by christian-intra2net** [comment]
I guess that is my fault. That exc_info there is redundant and can be removed
(logger.exception(...) is the same as logger.error(..., exc_info=True))

**Comment by christian-intra2net** [comment]
The original error is probably caused by a missing format-string number n ("{}".format(...) instead of "{n}".format(...)). There are "{}"s left in ppt_parser.py
