### ISSUE TITLE
olevba - bug with PDF/MHT

### ISSUE THREAD

**Issue by decalage2** [decalage2/oletools#822]
There seems to be a bug with olevba when scanning this sample:

- https://twitter.com/wdormann/status/1696197904262742370
- https://twitter.com/jpcert_en/status/1696056414148645326
- https://blogs.jpcert.or.jp/en/2023/08/maldocinpdf.html

Malware hash value

-     ef59d7038cfd565fd65bae12588810d5361df938244ebad33b71882dcf683058
-     098796e1b82c199ad226bff056b6310262b132f6d06930d3c254c57bdf548187
-     5b677d297fb862c2d223973697479ee53a91d03073b14556f421b3d74f136b9d

**Comment by decalage2** [comment]
This is a MIME parsing bug when calling `email.message_from_bytes`:
`_parse_headers` is called with a line without ":" and no leading whitespace.
This is probably due to the fact that this sample mixes MIME and PDF content.
```
INFO     Opening MHTML file 098796e1b82c199ad226bff056b6310262b132f6d06930d3c254c57bdf548187.doc
INFO     Failed MIME parsing for file '098796e1b82c199ad226bff056b6310262b132f6d06930d3c254c57bdf548187.doc' - Please report this issue on https://github.com/decalage2/oletools/issues
DEBUG    Trace:
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\site-packages\oletools\olevba.py", line 3053, in open_mht
    mhtml = email.message_from_bytes(stripped_data)
  File "C:\Program Files\Python39\lib\email\__init__.py", line 46, in message_from_bytes
    return BytesParser(*args, **kws).parsebytes(s)
  File "C:\Program Files\Python39\lib\email\parser.py", line 123, in parsebytes
    return self.parser.parsestr(text, headersonly)
  File "C:\Program Files\Python39\lib\email\parser.py", line 67, in parsestr
    return self.parse(StringIO(text), headersonly=headersonly)
  File "C:\Program Files\Python39\lib\email\parser.py", line 56, in parse
    feedparser.feed(data)
  File "C:\Program Files\Python39\lib\email\feedparser.py", line 176, in feed
    self._call_parse()
  File "C:\Program Files\Python39\lib\email\feedparser.py", line 180, in _call_parse
    self._parse()
  File "C:\Program Files\Python39\lib\email\feedparser.py", line 240, in _parsegen
    self._parse_headers(headers)
  File "C:\Program Files\Python39\lib\email\feedparser.py", line 524, in `
    assert i>0, "_parse_headers fed line with no : and no leading WS"
AssertionError: _parse_headers fed line with no : and no leading WS
```
